*/ * / * / * / * / * / * / * / * / * / * / * / * / * / * / 
*
*   Set paths & globals
*
* / * / * / * / * / * / * / * / * / * / * / * / * / * / *\

/* Description:
* 1. Define project globals and required folders
* 2. Check/install required user-written commands
* 3. Pull core PIP inputs used downstream
* 4. Run all pipeline do-files in order
*
* Input:
* 1. Local project folder structure under github/
* 2. Internet access for pip command calls
*
* Output:
* 1. Temp files in $output\temp:
*    - pip_incgroup.dta
*    - pip_all.dta
*    - pip_all_povlines.dta
*    - pip_wb_povlines.dta
* 2. Full pipeline outputs generated by 01-06 do-files
*/

gl path "PATH"
gl input "$path\02-input"
gl output "$path\03-output"
gl temp "$output\temp"


//create required folders
capture mkdir "$output"
capture mkdir "$output\temp"
capture mkdir "$output\graphs"


//install user-written commands if missing
capture which pip
if _rc {
	noi di as txt "Installing command: pip"
	capture ssc install pip, replace
}

capture which pip
if _rc {
	noi di as err "Command 'pip' is still missing. Install manually, then rerun 00-master.do."
	exit 199
}



//download PIP data
pip tables, table(country_list) clear 
ren country_code code
save "$temp\pip_incgroup.dta", replace

pip, clear fillgaps
ren country_code code
save "$temp\pip_all.dta", replace

pip, clear fillgaps povline(3, 4.2, 8.3)
ren country_code code
save "$temp\pip_all_povlines.dta", replace

pip wb, clear povline(3, 4.2, 8.3)
save "$temp\pip_wb_povlines.dta", replace


//run full replication pipeline
do "$path\01-do\01-mpo.do"
do "$path\01-do\02-emp_share.do"
do "$path\01-do\03-income_shock.do"
do "$path\01-do\04-price_shock.do"
do "$path\01-do\05-poverty.do"
do "$path\01-do\06-graphs.do"
